version: 2
preset:
  image: gantry-admin://images/layouts/default.png
  name: default
  timestamp: 1474265166
layout:
  /header/:
    -
      - 'system-messages-8489 100'
    -
      - 'logo-2371 56'
      - 'iconmenu-3709 44'
  /navigation/:
    -
      - 'menu-4987 80'
      - 'social-2827 20'
  /showcase/:
    -
      - 'position-showcase-6084 100'
    -
      - 'position-showcase-3677 33.3'
      - 'position-showcase-7689 33.3'
      - 'position-showcase-1657 33.3'
    -
      - 'position-showcase-3616 100'
  /container/:
    -
      -
        'body 67':
          -
            - 'system-content-7076 100'
      -
        'sidebar 33': {  }
  /extension/:
    -
      - 'position-extension-6976 100'
    -
      - 'position-extension-8215 33.3'
      - 'position-extension-7420 33.3'
      - 'position-extension-3240 33.3'
    -
      - 'position-extension-4690 100'
  /footer/:
    -
      - 'position-footer-3468 100'
    -
      - 'position-footer-8980 25'
      - 'position-footer-8721 25'
      - 'position-footer-8325 25'
      - 'position-footer-7290 25'
    -
      - 'position-footer-4360 100'
  /copyright/:
    -
      - 'position-copyright-7236 100'
    -
      - 'position-copyright-7911 33.3'
      - 'position-copyright-7615 33.3'
      - 'position-copyright-5730 33.3'
    -
      - 'position-copyright-4928 100'
  offcanvas:
    -
      - 'mobile-menu-8694 100'
structure:
  header:
    type: section
    subtype: header
    title: 'Header'
    attributes:
      id: g-header
      class: ''
      extra: {  }
      boxed: ''
  navigation:
    type: section
    subtype: nav
    title: 'Navigation'
    attributes:
      id: g-navigation
      class: ''
      extra: {  }
      boxed: ''
  showcase:
    type: section
    title: 'Showcase'
    attributes:
      id: g-showcase
      class: ''
      extra: {  }
      boxed: ''
  body:
    type: section
    subtype: main
    title: 'Content Body'
    attributes:
      id: g-body
      class: ''
      extra: {  }
      boxed: ''
    block:
      id: ''
      class: ''
      variations: ''
      fixed: ''
      size: '67'
  sidebar:
    type: section
    subtype: aside
    title: 'Sidebar'
    attributes:
      id: g-sidebar
      class: ''
      extra: {  }
      boxed: ''
    block:
      id: ''
      class: ''
      variations: ''
      fixed: ''
      size: '33'
  container:
    type: section
    title: 'Container'
    attributes:
      id: g-main
      class: ''
      extra: {  }
      boxed: ''
  extension:
    type: section
    title: 'Extension'
    attributes:
      id: g-extension
      class: ''
      extra: {  }
      boxed: ''
  footer:
    type: section
    title: 'Footer'
    attributes:
      id: g-footer
      class: ''
      extra: {  }
      boxed: ''
  copyright:
    type: section
    title: 'Copyright'
    attributes:
      id: g-copyright
      class: ''
      extra: {  }
      boxed: ''
  offcanvas:
    type: offcanvas
    attributes:
      id: g-offcanvas
      class: ''
      extra: {  }
      boxed: ''
      position: g-offcanvas-left
      swipe: 1
      css3animation: 1
content:
  system-messages-8489:
    type: system
    subtype: messages
    title: 'System Messages'
    attributes:
      enabled: true
    block:
      id: ''
      class: ''
      variations: ''
      fixed: ''
      size: '100'
  logo-2371:
    type: particle
    subtype: logo
    title: 'Logo / Image'
    attributes:
      enabled: true
      url: ''
      image: 'gantry-theme://images/logo/callisto.png'
      link: true
      svg: ''
      text: 'Callisto'
      class: 'g-logo'
    block:
      id: ''
      class: g-logo-block
      variations: ''
      fixed: ''
      size: '56'
  iconmenu-3709:
    type: particle
    subtype: iconmenu
    title: 'Icon Menu'
    attributes:
      enabled: true
      class: ''
      target: _parent
      items:
        -
          icon: 'fa fa-comments'
          text: 'Blog'
          link: 'https://blog.dazzlesoftware.org'
          name: Blog
        -
          icon: 'fa fa-book'
          text: 'Codex'
          link: 'https://codex.dazzlesoftware.org'
          name: Codex
        -
          icon: 'fa fa-commenting'
          text: 'Community'
          link: 'https://community.dazzlesoftware.org'
          name: Community
        -
          icon: 'fa fa-shopping-cart'
          text: 'Marketplace'
          link: 'https://marketplace.dazzlesoftware.org'
          name: Marketplace
    block:
      id: ''
      class: flush
      variations: ''
      fixed: ''
      size: '44'
  menu-4987:
    type: particle
    subtype: menu
    title: Menu
    attributes:
      enabled: true
      menu: ''
      base: '/'
      startLevel: 1
      maxLevels: 0
      renderTitles: 0
      hoverExpand: 1
      mobileTarget: 0
    block:
      id: ''
      class: g-menu-block
      variations: ''
      fixed: ''
      size: '80'
  social-2827:
    type: particle
    subtype: social
    title: Social
    attributes:
      enabled: true
      css:
        class: 'social-items'
      title: ''
      target: _blank
      display: both
      items:
        -
          icon: 'fa fa-twitter fa-fw'
          text: ''
          link: 'http://www.twitter.com/dazzlesoftware'
          name: Twitter
        -
          icon: 'fa fa-facebook fa-fw'
          text: ''
          link: 'http://www.facebook.com/dazzlesoftware'
          name: Facebook
        -
          icon: 'fa fa-google-plus fa-fw'
          text: ''
          link: 'https://plus.google.com/u/0/106840830150956948495'
          name: Google+
    block:
      id: ''
      class: ''
      variations: ''
      fixed: ''
      size: '20'
  position-showcase-6084:
    type: particle
    subtype: position
    title: 'Position - Showcase Top'
    attributes:
      enabled: true
      key: showcase-top
      chrome: ''
    block:
      id: ''
      class: 'flush'
      variations: ''
      fixed: ''
      size: '100'
  position-showcase-3677:
    type: particle
    subtype: position
    title: 'Position - Showcase A'
    attributes:
      enabled: true
      key: showcase-a
      chrome: ''
    block:
      id: ''
      class: 'flush'
      variations: ''
      fixed: ''
      size: '33.3'
  position-showcase-7689:
    type: particle
    subtype: position
    title: 'Position - Showcase B'
    attributes:
      enabled: true
      key: showcase-b
      chrome: ''
    block:
      id: ''
      class: 'flush'
      variations: ''
      fixed: ''
      size: '33.3'
  position-showcase-1657:
    type: particle
    subtype: position
    title: 'Position - Showcase C'
    attributes:
      enabled: true
      key: showcase-c
      chrome: ''
    block:
      id: ''
      class: 'flush'
      variations: ''
      fixed: ''
      size: '33.3'
  position-showcase-3616:
    type: particle
    subtype: position
    title: 'Position - Showcase Bottom'
    attributes:
      enabled: true
      key: showcase-bottom
      chrome: ''
    block:
      id: ''
      class: 'flush'
      variations: ''
      fixed: ''
      size: '100'
  system-content-7076:
    type: system
    subtype: content
    title: 'Page Content'
    attributes:
      enabled: true
    block:
      id: ''
      class: nomarginall
      variations: box2
      fixed: ''
      size: '100'
  position-extension-6976:
    type: particle
    subtype: position
    title: 'Position - Extension Top'
    attributes:
      enabled: true
      key: extension-top
      chrome: ''
    block:
      id: ''
      class: 'center flush'
      variations: ''
      fixed: ''
      size: '100'
  position-extension-8215:
    type: particle
    subtype: position
    title: 'Position - Extension A'
    attributes:
      enabled: true
      key: extension-a
      chrome: ''
    block:
      id: ''
      class: 'flush'
      variations: ''
      fixed: ''
      size: '33.3'
  position-extension-7420:
    type: particle
    subtype: position
    title: 'Position - Extension B'
    attributes:
      enabled: true
      key: extension-b
      chrome: ''
    block:
      id: ''
      class: 'flush'
      variations: ''
      fixed: ''
      size: '33.3'
  position-extension-3240:
    type: particle
    subtype: position
    title: 'Position - Extension C'
    attributes:
      enabled: true
      key: extension-c
      chrome: ''
    block:
      id: ''
      class: 'flush'
      variations: ''
      fixed: ''
      size: '33.3'
  position-extension-4690:
    type: particle
    subtype: position
    title: 'Position - Extension Bottom'
    attributes:
      enabled: true
      key: extension-bottom
      chrome: ''
    block:
      id: ''
      class: 'center flush'
      variations: ''
      fixed: ''
      size: '100'
  position-footer-3468:
    type: particle
    subtype: position
    title: 'Position - Footer Top'
    attributes:
      enabled: true
      key: footer-top
      chrome: ''
    block:
      id: ''
      class: 'center flush'
      variations: ''
      fixed: ''
      size: '100'
  position-footer-8980:
    type: particle
    subtype: position
    title: 'Position - Footer A'
    attributes:
      enabled: true
      key: footer-a
      chrome: ''
    block:
      id: ''
      class: 'flush'
      variations: ''
      fixed: ''
      size: '25'
  position-footer-8721:
    type: particle
    subtype: position
    title: 'Position - Footer B'
    attributes:
      enabled: true
      key: footer-b
      chrome: ''
    block:
      id: ''
      class: 'flush'
      variations: ''
      fixed: ''
      size: '25'
  position-footer-8325:
    type: particle
    subtype: position
    title: 'Position - Footer C'
    attributes:
      enabled: true
      key: footer-c
      chrome: ''
    block:
      id: ''
      class: 'flush'
      variations: ''
      fixed: ''
      size: '25'
  position-footer-7290:
    type: particle
    subtype: position
    title: 'Position - Footer D'
    attributes:
      enabled: true
      key: footer-d
      chrome: ''
    block:
      id: ''
      class: 'flush'
      variations: ''
      fixed: ''
      size: '25'
  position-footer-4360:
    type: particle
    subtype: position
    title: 'Position - Footer Bottom'
    attributes:
      enabled: true
      key: footer-bottom
      chrome: ''
    block:
      id: ''
      class: 'center flush'
      variations: ''
      fixed: ''
      size: '100'
  position-copyright-7236:
    type: particle
    subtype: position
    title: 'Position - Copyright Top'
    attributes:
      enabled: true
      key: copyright-top
      chrome: ''
    block:
      id: ''
      class: 'center flush'
      variations: ''
      fixed: ''
      size: '100'
  position-copyright-7911:
    type: particle
    subtype: position
    title: 'Position - Copyright A'
    attributes:
      enabled: true
      key: copyright-a
      chrome: ''
    block:
      id: ''
      class: 'flush'
      variations: ''
      fixed: ''
      size: '33.3'
  position-copyright-7615:
    type: particle
    subtype: position
    title: 'Position - Copyright B'
    attributes:
      enabled: true
      key: copyright-b
      chrome: ''
    block:
      id: ''
      class: 'flush'
      variations: ''
      fixed: ''
      size: '33.3'
  position-copyright-5730:
    type: particle
    subtype: position
    title: 'Position - Copyright C'
    attributes:
      enabled: true
      key: copyright-c
      chrome: ''
    block:
      id: ''
      class: 'flush'
      variations: ''
      fixed: ''
      size: '33.3'
  position-copyright-4928:
    type: particle
    subtype: position
    title: 'Position - Copyright Bottom'
    attributes:
      enabled: true
      key: copyright-bottom
      chrome: ''
    block:
      id: ''
      class: 'center flush'
      variations: ''
      fixed: ''
      size: '100'
  mobile-menu-8694:
    type: particle
    subtype: mobile-menu
    title: 'Mobile Menu'
    attributes:
      enabled: true
    block:
      id: ''
      class: ''
      variations: ''
      fixed: ''
      size: '100'